# Computation Excercise:HMM

 On the file provided on BCourses (Xtrain.csv), we
recorded transitions of a Markov Chain with the states {${1,.....,10}$} that evolves
over $N = 20$ time periods. The initial state was chosen randomly according
to some probability distribution q() and the transitions are governed by some
transition matrix P. We recorded 10000 of such sequences.

In addition, for each state sequence we recorded a sequence of observations
of each state. The observations $z_k$ {${1,.....,10}$} may be inaccurate. Hence,
for a given state $x_k$ we have that the observation z_k follows some distribu-
tion $r(z_k = j|x_k=i)$. We recorded 10000 of such observation trajectories on the file
Ztrain.csv (also on BCourses).



In [1]:
import pandas as pd             
import numpy as np                     
import os
os.listdir()


C:\Users\tugba\Anaconda3\lib\site-packages\pysal\explore\segregation\network\network.py:16: UserWarning: You need pandana and urbanaccess to work with segregation's network module
You can install them with  `pip install urbanaccess pandana` or `conda install -c udst pandana urbanaccess`
  "You need pandana and urbanaccess to work with segregation's network module\n"


['.ipynb_checkpoints',
 'Homework_1_265.pdf',
 'Learning and Optimization HW1.ipynb',
 'Xtest.csv',
 'Xtrain.csv',
 'Ztest.csv',
 'Ztrain.csv']

In [2]:
#read required files 
X_train = pd.read_csv('Xtrain.csv',header=None)
X_test = pd.read_csv('Xtest.csv',header=None)
Z_train = pd.read_csv('Ztrain.csv',header=None)
Z_test = pd.read_csv('Ztest.csv',header=None)



#### Probability Transition Matrix 

In [3]:
## Columns are time frames and rows are observations
X_train.head()


0   1   2   3   4   5   6   7   8   9   ...  11  12  13  14  15  16  17  \
0   7   9   7   6   2   5   2   3   7   1  ...   1   2   9  10   8   2   2   
1   1   1   1   7   9   1   5   2   1   7  ...   2   3   5   2   3   8   4   
2   1   1  10   3   2   7   5   4   2   7  ...   7   8  10   2  10   4  10   
3   7   2   1   2   4   7   2   5   6   2  ...   2  10   5   1   4   9   9   
4   8   5   2   7   8   5   2  10   3   9  ...   1   8   3  10  10   3   5   

   18  19  20  
0   3   2   3  
1   6   7   8  
2  10   9   8  
3   2   9   7  
4   4   6   2  

[5 rows x 21 columns]

In [4]:
Z_train.head()



0   1   2   3   4   5   6   7   8   9   ...  11  12  13  14  15  16  17  \
0   7   5   7   6   2   5   3   3   7   1  ...   1   2   8  10   8   5   2   
1   1   1   1   7   9   1   5   5   1   8  ...   2   7   5   2   3   8   4   
2   1   6  10   8   2   7   5   4   2   7  ...   2   9  10   2  10   4  10   
3   7   8   1   2   4   7   2   5   6   2  ...   6   8   3   1   4   9   9   
4   8   5   2   7   8   5   2  10   3   9  ...   7   8   3  10   4   1  10   

   18  19  20  
0   3   2   1  
1   3   9   8  
2   8  10   8  
3   2   9   7  
4   4  10   2  

[5 rows x 21 columns]

In [5]:
m = np.array(X_train)
P = np.zeros((10,10))
total=0
for i in range(len(m)):
    for j in range(20):
        
        state_1 = m[i,j]
        state_2 = m[i,j+1]
        
        P[state_1-1,state_2-1] = P[state_1-1,state_2-1] + 1
        total=total+1
        
P = P/total


#### Probability Distribution
lastly $q_{0}^{i}$ counts across all trajectories, the number of times the markov chain started at state i.



In [6]:
i = np.array(X_train.iloc[:,0])
v = np.zeros((10,1))
total = 0 
for record in range(len(i)):
    state_0 = i[record]
    v[state_0-1] = v[state_0-1] + 1 
    total = total +1
v=v/total

#### Conditional Probabilities

$n_{i,j}$ counts across all trajectories, the number of
times the observation made was j when the hidden state was i;




In [7]:
Z_train.head(5)



0   1   2   3   4   5   6   7   8   9   ...  11  12  13  14  15  16  17  \
0   7   5   7   6   2   5   3   3   7   1  ...   1   2   8  10   8   5   2   
1   1   1   1   7   9   1   5   5   1   8  ...   2   7   5   2   3   8   4   
2   1   6  10   8   2   7   5   4   2   7  ...   2   9  10   2  10   4  10   
3   7   8   1   2   4   7   2   5   6   2  ...   6   8   3   1   4   9   9   
4   8   5   2   7   8   5   2  10   3   9  ...   7   8   3  10   4   1  10   

   18  19  20  
0   3   2   1  
1   3   9   8  
2   8  10   8  
3   2   9   7  
4   4  10   2  

[5 rows x 21 columns]

In [8]:
r = np.zeros((10,10))
total = 0
z = np.array(Z_train)
for record in range(len(z)):
    for time in range(20):
        state_1 = m[record,time] 
        
        observation = z[record,time]
        
        ##Find a way to represent this as an array rows:(i,j) pairs columns:(z)    
        
        r[state_1-1,observation-1] = r[state_1-1,observation-1] + 1 
        total = total +1
        
        
r=r/total




In [173]:
print('initial state probabilities:\n',v)
print('sum of initial state probabilities',np.sum(v))

print("\n Initial Stage Shape",v.shape)






initial state probabilities:
 [[0.0962 0.0989 0.0993 0.1017 0.1016 0.1049 0.1009 0.098  0.1033 0.0952]]
sum of initial state probabilities 1.0

 Initial Stage Shape (1, 10)


In [174]:
print("\n Conditional Probabilities:\n",r)
print('sum of conditional probabilities',np.sum(r))
print("\n Conditional Probabilities r(z_i|x_i) Shape",r.shape)




 Conditional Probabilities:
 [[0.09806  0.00258  0.00266  0.002795 0.00286  0.002635 0.002685 0.002745
  0.002915 0.002805]
 [0.002375 0.08409  0.002455 0.002215 0.002355 0.002195 0.002335 0.00235
  0.00246  0.00216 ]
 [0.001615 0.00184  0.06433  0.00179  0.001715 0.00171  0.001895 0.001835
  0.001815 0.00182 ]
 [0.00288  0.002665 0.002585 0.09586  0.0025   0.002745 0.00268  0.00263
  0.00257  0.002585]
 [0.002385 0.0024   0.00251  0.002235 0.084935 0.002345 0.0026   0.002285
  0.0023   0.00239 ]
 [0.002085 0.001915 0.00192  0.001845 0.00207  0.06892  0.0019   0.002105
  0.00174  0.00203 ]
 [0.0027   0.0027   0.00268  0.00282  0.002665 0.00257  0.097675 0.002685
  0.00288  0.00263 ]
 [0.00156  0.00177  0.00163  0.00175  0.001705 0.001635 0.00168  0.06042
  0.001595 0.00173 ]
 [0.00169  0.001795 0.00176  0.00181  0.001785 0.001625 0.00176  0.00168
  0.06364  0.001815]
 [0.       0.00241  0.00245  0.002345 0.00238  0.002315 0.002255 0.002415
  0.00225  0.08363 ]]
sum of conditional prob

In [175]:
print("\n Transition Matrix:\n", P)
print('sum of transition probabilities',np.sum(P))
print("\n Transitions P(x_i,x_i+1) Shape",P.shape)


 Transition Matrix:
 [[2.0945e-02 1.0045e-02 7.1700e-03 2.0370e-02 8.3850e-03 1.2330e-02
  1.3940e-02 1.1015e-02 6.4600e-03 1.2080e-02]
 [1.7010e-02 3.2950e-03 1.3865e-02 1.3615e-02 1.4295e-02 1.4800e-03
  1.7135e-02 2.0600e-03 5.8300e-03 1.6405e-02]
 [9.5000e-03 9.6100e-03 6.5000e-05 1.0245e-02 1.3800e-02 1.8350e-03
  7.1050e-03 1.1230e-02 1.3760e-02 3.2150e-03]
 [1.1085e-02 1.6790e-02 1.6570e-02 1.1975e-02 1.4095e-02 1.3100e-02
  1.2325e-02 1.2800e-03 1.2905e-02 9.5750e-03]
 [1.7880e-02 1.9415e-02 6.9450e-03 1.7820e-02 8.8100e-03 2.5450e-03
  1.9740e-02 1.8250e-03 2.2100e-03 9.1950e-03]
 [6.6900e-03 1.8720e-02 9.8200e-03 6.1850e-03 1.5150e-02 1.5470e-02
  1.1780e-02 9.0000e-04 1.5000e-04 1.6650e-03]
 [9.5300e-03 1.5580e-02 2.3000e-04 6.4350e-03 1.1250e-02 1.7420e-02
  1.8155e-02 1.4740e-02 1.5155e-02 1.3510e-02]
 [1.2780e-02 1.8900e-03 5.6450e-03 3.8350e-03 5.4800e-03 9.5650e-03
  4.3150e-03 9.6100e-03 4.6650e-03 1.7690e-02]
 [1.3130e-02 9.8300e-03 5.4550e-03 1.5175e-02 1.1100e-02 5

#### Viterbi Algorithm for State Estimation

In [86]:
def viterbi(P, v, r, Z):
    
    I = P.shape[0]    # number of states
    N = Z.shape[1]  # length of observation sequence
    
    # initialize D and E matrices
    D = np.zeros([I, N])
    E = np.zeros([I, N-1])
    D[:, 0] = np.multiply(v, r[:, Z[0,0]])
    
    # compute D and E in a nested loop
    for n in range(1, N):
        for i in range(I):
            temp_product = np.multiply(P[:, i], D[:, n-1])
            D[i,n] = np.amax(temp_product) * r[i, Z[0, n]-1]
            E[i, n-1] = np.argmax(temp_product)
            
    max_ind = np.zeros([1, N])
    max_ind[0, -1] = np.argmax(D[:, -1])
    
    # Backtracking
    for n in range(N-2, 0, -1):
        max_ind[0, n] = E[int(max_ind[0, n+1]), n]
    
    # Convert zero-based indices to state indices
    S_opt = max_ind.astype(int)+1
    
    return S_opt

Z = np.array(Z_test)
v= v.reshape(1,10)
optimal_sequence = viterbi(P,v,r,Z)
X = np.array(X_test)

print(optimal_sequence)
print(X)

[[ 1  9  7  6  2  4  2  3  7  9  8  1  6  2 10  8  1  2  3  2  3]]
[[ 4  1  4  5  4  2  5  7  9  1 10  9  4  4  7  7  8  7 10 10  8]]


In [66]:
# ## Create a conditional probability matrix is it shape 10,10 ? 
# ## Somehow I have to create the trellis diagram, assigne path costs for each possible path 

# ## Among all possible paths, find the path with shortest length. I have no idea how to implement it as a code. 

# #-np.log(P*r[:,Z[0]-1])

# #np.log(v*r[:,Z[0]])

# Z = np.array(Z_test).reshape(21,)

# p = 10 
# k = 21

# Cost = np.zeros((p,k))

# Prev = np.zeros((p, k))

# g_0 = -np.log(v.T * r[:,Z[0]])

# Cost[:,0] = g_0

# print(np.log(P[:,i]*r[:,Z[n]]).shape)
# print(Cost.shape)

(10,)
(10, 21)


#### Forward-Backward Algorithm to Estimate State X20 given Z1,......,20

In [164]:
alphas = np.empty((len(z[0]),10))

betas = np.empty((len(z[0]),10))

alphas[0,:] = v*r[:,Z[0,0]-1]

betas[20,:] = np.array([1,1,1,1,1,1,1,1,1,1]) 



for i in range(1,21):
    R = np.zeros((10,10))
    for j in range(10):

        R[j,j] = r[j,Z[0,i]-1]
    
    alphas[i,:] = np.matmul(np.matmul(alphas[i-1],P),R)
    
for i in range(1,21):
    R = np.zeros((10,10))
    for j in range(10):
        R[j,j] = r[j,Z[0,20-i]-1] ##Create the diagonal R matrix where [j,j] element is r(z_k|x_k=j)
    
    betas[20-i,:] = np.matmul(np.matmul(betas[21-i],P),R)
    
P_20 = alphas[20,:] * betas[20,:] / np.sum(alphas[20,:] * betas[20,:])

print("Given ZN, most likely state for x_20 is",np.where(P_20 == np.max(P_20))[0][0]+1)









Given ZN, most likely state for x_20 is 3


#### P(ZN)

In [172]:
np.sum(np.matmul(alphas,betas.T))

0.011848966212157296